version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./
      target: development
    command: npm run start:debug
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/src
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    logging:
      driver: none

volumes:
  postgres:
    driver: local
